"""add language to posts

Revision ID: 276c2ab5ba82
Revises: 8786752389d4
Create Date: 2025-05-12 16:27:18.096493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '276c2ab5ba82'
down_revision = '8786752389d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
